### PR TITLE
Move instructor-notes to episodes.

### PR DESCRIPTION
**Pull request by albhasan**
Move the notes in `instructors/instructor-notes.md` to their corresponding episodes.

### CODE REVIEW

**Review by mikemahoney218 — APPROVED** [review]
See also #133, #134 (just for my sake -- I like being able to trace these sorts of efforts over time :smile:)

Looks great from where I'm sitting!

**Comment by likeajumprope** [comment]
Looks great from my side as well - merging this PR

**Comment by likeajumprope** [comment]
I somehow do not seem to be able to merge this PR - can you @mikemahoney218?

**Review by likeajumprope — COMMENTED** [review]
Looks fine

**Review by likeajumprope — APPROVED** [review]

**Pull request merged**
