### PR TITLE
Added missing curly braces in 02-project-intro.Rmd

### PR DESCRIPTION
**Pull request by lquayle88**

### CODE REVIEW

**Comment by mikemahoney218** [comment]
I'm curious what this will actually return -- I think it's often some crazy temporary directory path, though I don't actually know our CI well enough to know that without seeing it. 

Do we think seeing a different path will confuse learners? Alternatively, might we consider also changing the text right after this box to something like `Your working directory will be different from this one! On your computer, this should return a path like your/path/r-geospatial instead.`

**Comment by jsta** [comment]
@mikemahoney218 The following line reads `R should return your/path/r-geospatial as the working directory.` Makes me wonder if the curly braces were left off on purpose to avoid confusion.

**Comment by lquayle88** [comment]
@mikemahoney218 if you just run `getwd()` it returns the path to your home directory. Given that the preceding instructions create a new r-geospatial project, running `getwd()` returns the full path to that new project top-level. The following line therefore makes total sense. As to whether the missing curly braces were intentional 🤷

**Comment by mikemahoney218** [comment]
Yeah, this strikes me as probably being intentional, considering that the home directory _on a GitHub Actions runner_ won't correspond to the learner's file system ([Google suggests](https://dev.to/mihinduranasinghe/working-with-environment-variables-github-actions-part-2-46po) it was `/home/runner/work/<repo>/<repo>` two years ago, but it's not in the docs anywhere I can see so is probably liable to change), and we have the text immediately after saying what the command should return. 

Thank you very much for the PR! But I think in order to minimize learner confusion, it's probably best to keep this without the brackets for the moment being.

**Pull request closed without merging**
