### PR TITLE
Cuts to remaining episodes

### PR DESCRIPTION
**Pull request by ErinBecker**
Makes suggested cuts as in https://github.com/datacarpentry/r-intro-geospatial/issues/22 to:

- writing good software
- manipulating dataframes with dplyr
- creating publication-quality graphics with ggplot

Also rebuilds site to show these changes.

Replaces:
- https://github.com/datacarpentry/r-intro-geospatial/pull/32
- https://github.com/datacarpentry/r-intro-geospatial/pull/31

### CODE REVIEW

**Comment by lwasser** [comment]
this looks good to me too. i'd like to see what others think. my only question -t he last episode on writing good software seems important even if it's not explicitly taught. i wonder about leaving as an optional review lesson. there isnt time for all of these lessons however in 2 days with the geospatial stuff regardless :) it's just optional for folks. thoughts everyone?

**Comment by ErinBecker** [comment]
@lwasser - thanks for the thoughts! My recommendation is to avoid "optional lessons" whenever possible, as we want to provide a clear pathway for what is the "canonical workshop" for this curriculum. The writing good software episode was written with the perspective that people in the audience would be doing just that (writing their own software packages), but I don't think that's the expectation we have of these learners (if it is please correct me!). 

The main idea with cutting down these R lessons so heavily is that they will be able to be taught in full in a two day workshop, along with the raster vector lesson. I think we only want to include information in this intro R lesson that is absolutely required in order for learners to be able to do the raster vector lesson, which is why I would recommend making this cut. 

I'll of course leave this up to the Maintainers, but that is my recommendation.

**Comment by fmichonneau** [comment]
@ErinBecker for this repository, Travis takes care of building and deploying the website, so no need to commit changes associated with rebuilding the lesson.

**Comment by lwasser** [comment]
That sounds reasonable to me, erin!

**Comment by ErinBecker** [comment]
Given the approval from @lwasser and no objections from others, I'll go ahead and merge this.

**Pull request merged**
